name: Create and release document PDF

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Build and release PDF
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - uses: lerenner/mac0499-latex-cicd@v2
        with:
          output: "builds"

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tese.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
