name: Create and release document PDF

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Build and release PDF
    runs-on: ubuntu-latest
    steps:
          
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Build dissertation PDF
        uses: lerenner/mac0499-latex-cicd@v5

      - uses: actions/upload-artifact@v4
        with:
          name: dissertation-pdf
          path: tese.pdf
